### ISSUE TITLE
'ViCareClimate' object has no attribute '_current_operation'

### ISSUE THREAD

**Issue by vandenberghev** [openviess/PyViCare#11]
'ViCareClimate' object has no attribute '_current_operation'

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 330, in _handle_service_platform_call
    await func(entity, data)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 564, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/vicare/climate.py", line 216, in set_temperature
    self._api.setProgramTemperature(self._current_operation, self._target_temperature)
AttributeError: 'ViCareClimate' object has no attribute '_current_operation'

**Comment by vandenberghev** [comment]
Crap, I meant to create this @ oischinger/ha_vicare... Sorry!
