### ISSUE TITLE
Strange error on Raspberry pi 3 

### ISSUE THREAD

**Issue by sebwaks** [openviess/PyViCare#12]
identical code identical PyViCare on mac works ,any help pointer would be appreciated .

pi@raspberrypi:/home/backend/probes$ python3.7
Python 3.7.2 (default, Feb 17 2019, 21:49:47)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyViCare import ViCareSession
>>> t=ViCareSession("email@mydomain.com","password","token.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCare.py", line 53, in __init__
    self._getInstallations()
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCare.py", line 200, in _getInstallations
    self.installations = self.__get(apiURLBase+"/general-management/installations?expanded=true&")
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCare.py", line 145, in __get
    r=self.oauth.get(url).json()
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by sebwaks** [comment]
i=t.getInstallations() :)
