### ISSUE TITLE
Functions stops working

### ISSUE THREAD

**Issue by prior-philip** [openviess/PyViCare#158]
It seems that some functions seems to stop working with current release of PyViCare.

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 42, in getDomesticHotWaterConfiguredTemperature
    return self.service.getProperty("heating.dhw.temperature")["properties"]["value"]["value"]
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ViCare/ViCare_API2MQTT.py", line 162, in <module>
    run()
  File "/opt/ViCare/ViCare_API2MQTT.py", line 157, in run
    publish(client)
  File "/opt/ViCare/ViCare_API2MQTT.py", line 116, in publish
    dictVito=get_VitoValues()
  File "/opt/ViCare/ViCare_API2MQTT.py", line 55, in get_VitoValues
    getDomesticHotWaterConfiguredTemperature=t.getDomesticHotWaterConfiguredTemperature(),
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 22, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 17, in wrapper
    raise PyViCareNotSupportedFeatureError(func.__name__)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: getDomesticHotWaterConfiguredTemperature
```

Is that anything that I can solve on my end? I see that "getDomesticHotWaterConfiguredTemperature" is part of PyViCareDevice.py. So whats the issue? I didnt try every function but at least several "gets" are affected

**Comment by woehrl01** [comment]
Hi @prior-philip 

This is due to the noted breaking change in the Readme, that on not supported features a `PyViCareNotSupportedFeatureError` is thrown. It simply means that your device does not return values via the new Viessmann API.

Before it just returned `error` as string which doesn't created your output. 

You can either add a `try/except` block or use `suppress` from `contextlib`.

**Comment by prior-philip** [comment]
Hi @woehrl01 
okay. I was sure these features exists but it seems you are right. But when setting OneTimeCharge to "true" it also fails with "COMMAND NOT EXECUTABLE" - That worked before. I promise ;)

```
 File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 42, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 177, in deactivateOneTimeCharge
    return self.service.setProperty("heating.dhw.oneTimeCharge", "deactivate", {})
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 27, in setProperty
    response = super().setProperty(property_name, action, data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 49, in setProperty
    return self.oauth_manager.post(url, post_data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 80, in post
    self.__handle_command_error(response)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 56, in __handle_command_error
    raise PyViCareCommandError(response)
PyViCare.PyViCareUtils.PyViCareCommandError: (PyViCareCommandError(...), 'Command failed with status code 502. Reason given was: COMMAND_NOT_EXECUTABLE')
```

**Comment by BrechtMo** [comment]
I think Viessmann made some changes to the API concerning hot water readouts. 
This happened in the last couple of days.

One example:

To get the top temperature of my vitocell solar boiler I now have to query
`heating.dhw.sensors.temperature.hotWaterStorage`

where before it was 
`heating.boiler.sensors.temperature.main`
(doesn't work anymore)

this also broke some Home Assistant functionality relying on the old features.

**Comment by prior-philip** [comment]
> Hi @prior-philip
> 
> This is due to the noted breaking change in the Readme, that on not supported features a `PyViCareNotSupportedFeatureError` is thrown. It simply means that your device does not return values via the new Viessmann API.
> 
> Before it just returned `error` as string which doesn't created your output.
> 
> You can either add a `try/except` block or use `suppress` from `contextlib`.

Is is planned to funnel such exception into a message ("error" is fine for me) rather than breaking the process?
BrechtMo already mentioned that feature paths are changing. Catching them a controlled way would help the users a lot to keep their scripts running,

**Comment by woehrl01** [comment]
@prior-philip [As described in the readme](https://github.com/somm15/PyViCare#breaking-changes-in-version-1x), currently feature flags are available to switch back to the old behaviour (see `Feature.raise_exception_on_not_supported_device_feature`)

[See the following test for an example how to use it.](https://github.com/somm15/PyViCare/blob/6a65f6f9902142584dce8821705e86223e5054a3/tests/test_Vitodens200W.py#L40-L42)

There is currently a thread to discuss removing the older feature flags, see #155 

From a future perspective, it's pretty likely that the exception will be the only solution. The feature flag is available to remove the burden to switch right now.

**Comment by woehrl01** [comment]
I'll close the issue for now. Please share your opinion regarding the feature flag removal in #155 .
