### ISSUE TITLE
Improve debug on invalid responses

### ISSUE THREAD

**Issue by woehrl01** [openviess/PyViCare#179]
As mentioned in https://github.com/oischinger/ha_vicare/issues/49 there is a not really helpful error if something is wrong on the initial device reading.

**Comment by oischinger** [comment]
I just had the same issue. Never occured before.
```2021-09-03 20:40:08 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ViCare for vicare
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vicare/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vicare/__init__.py", line 118, in setup_vicare_api
    vicare_api.initWithCredentials(
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 24, in initWithCredentials
    self.initWithExternalOAuth(ViCareOAuthManager(
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 29, in initWithExternalOAuth
    self.__loadInstallations()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCare.py", line 43, in __loadInstallations
    self.devices = list(self.__readInstallations(installations["data"]))
KeyError: 'data'
```

**Comment by woehrl01** [comment]
Is this reproducible for you? I would be interested in what is the actual response.

**Comment by oischinger** [comment]
unfortunately not. I only got it once.

**Comment by woehrl01** [comment]
I can reproduce it currently the server returns an internal error 500. I added a better output. But this can't be solved form our side.
