### ISSUE TITLE
TypeError resp. unhandled exception when calling probably unsupported features

### ISSUE THREAD

**Issue by skahlhoefer** [openviess/PyViCare#257]
Hi there,

I'm using Home Assistant and recently added the ViCare integration which seems to be heavily based on this great module.
While trying to make use of the domestic hot water one time charge, I received a TypeError which has been Home Assistant wise logged as the following issue: https://github.com/home-assistant/core/issues/73064

Doing some further personal investigation I found out that the exact same error occurs as well when using PyViCare directly.

```
>>> t.activateOneTimeCharge()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 283, in activateOneTimeCharge
    return self.service.setProperty("heating.dhw.oneTimeCharge", "activate", {})
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 29, in setProperty
    response = super().setProperty(property_name, action, data)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 60, in setProperty
    return self.oauth_manager.post(url, post_data)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 91, in post
    self.__handle_command_error(response)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 67, in __handle_command_error
    raise PyViCareCommandError(response)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 124, in __init__
    reason = extended_payload["reason"]
KeyError: 'reason'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 65, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 60, in wrapper
    raise PyViCareCommandError(func.__name__)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 121, in __init__
    statusCode = response["statusCode"]
TypeError: string indices must be integers
>>>
```

The root cause may be that my specific heating model doesn't support this API function but if so, it should in my opinion be handled with an appropriate exception as in the module function getOneTimeCharge.

```
>>> t.getOneTimeCharge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 275, in getOneTimeCharge
    return self.service.getProperty("heating.dhw.oneTimeCharge")["properties"]["active"]["value"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.dhw.oneTimeCharge
```

**Comment by woehrl01** [comment]
Just published `2.16.3` including a fix. Thanks for reporting @skahlhoefer !

**Comment by skahlhoefer** [comment]
Wow, that was extremely fast. Thanks for that @woehrl01 !

**Comment by woehrl01** [comment]
You're welcome @skahlhoefer
