### ISSUE TITLE
How to catch errors raised by PyViCare

### ISSUE THREAD

**Issue by peterwalber** [openviess/PyViCare#344]
I use PyViCare to access my viessmann API. It works fine but from time to time PyViCare raises an error message.

I Use the code 

` vicare = PyViCare()
  vicare.initWithCredentials(email, password, client_id, "token.save")
  device = vicare.devices[0]
  t = device.asAutoDetectDevice()

  temp_outside = t.getOutsideTemperature()`

from time to time I get the error message

`Traceback (most recent call last):
  File "/home/peter/viessmann/viessmann-monitoring-gasverbrauch.py", line 65, in <module>
    temp_outside = t.getOutsideTemperature()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareUtils.py", line 55, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareUtils.py", line 48, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareHeatingDevice.py", line 70, in getOutsideTemperature
    return self.service.getProperty("heating.sensors.temperature.outside")["properties"]["value"]["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareCachedService.py", line 24, in getProperty
    data = self.__get_or_update_cache()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareCachedService.py", line 42, in __get_or_update_cache
    data = self.fetch_all_features()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareService.py", line 64, in fetch_all_features
    return self.oauth_manager.get(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 41, in get
    self.__handle_server_error(response)
  File "/home/peter/viessmann/lib/python3.11/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 63, in __handle_server_error
    raise PyViCareInternalServerError(response)
PyViCare.PyViCareUtils.PyViCareInternalServerError: (PyViCareInternalServerError(...), 'Request failed with status code 502 and message "Your request could not be performed as there was a problem with external service". ViCare ErrorId: req-a5b5a4a1bd374743881640322d1e4bb8')
`

How can I handle such an error in order to avoid that the program stops.

**Comment by fredtj** [comment]
@peterwalber https://www.w3schools.com/python/python_try_except.asp

**Comment by woehrl01** [comment]
As @fredtj thankfully suggested, please use the built in mechanisms of python to "catch" and handle the exceptions gracefully.
