### ISSUE TITLE
KeyError: 'entities'

### ISSUE THREAD

**Issue by bzc0fq** [openviess/PyViCare#37]
Hi,
I use PyViCare for a few days. I get KeyError: 'entities' errors from time to time.
Please see messages bellow:

Traceback (most recent call last):
  File "load_temperature_VITODENS.py", line 8, in <module>
    t=GazBoiler('xxxxxxx','xxxxxxx','/tmp/vicare_token.save') 
  File "/root/PyViCare/PyViCareDevice.py", line 46, in __init__
    self.service = ViCareService(username, password, token_file, circuit)
  File "/root/PyViCare/PyViCareService.py", line 58, in __init__
    self._getInstallations()
  File "/root/PyViCare/PyViCareService.py", line 219, in _getInstallations
    self.id=self.installations["entities"][0]["properties"]["id"]
KeyError: 'entities'

Could you please investigate the issue? (I have enabled debugging but did not receive error messages since this morning).

Thanks 

-----------------
UPDATE1

OK. I got the errors reoccurred. Please find logs attached bellow:

2020-09-30 09:50:23,441 ViCare       INFO     Token file exists
2020-09-30 09:50:23,451 ViCare       INFO     Token restored from file
2020-09-30 09:50:23,454 ViCare       DEBUG    <requests_oauthlib.oauth2_session.OAuth2Session object at 0xb620dff0>
2020-09-30 09:50:24,693 ViCare       DEBUG    Response to get request: {'statusCode': 401, 'errorType': 'UNAUTHORIZED', 'error': 'EXPIRED TOKEN', 'message': 'Token provided in request is expired or invalid.', 'viErrorId': 'req-e0a9099968da457fa5b00d5431abc0f3'}
Traceback (most recent call last):
  File "load_temperature_VITODENS.py", line 22, in <module>
    t=GazBoiler('xxxxx','xxxxx','/tmp/vicare_token.save') 
  File "/root/PyViCare/PyViCareDevice.py", line 46, in __init__
    self.service = ViCareService(username, password, token_file, circuit)
  File "/root/PyViCare/PyViCareService.py", line 58, in __init__
    self._getInstallations()
  File "/root/PyViCare/PyViCareService.py", line 219, in _getInstallations
    self.id=self.installations["entities"][0]["properties"]["id"]
KeyError: 'entities' 

Any thoughts on this?

**Comment by somm15** [comment]
Did you set the cache duration? 
By default, GazBoiler will use 0 as cache time and don't cache anything.
You could then just be rejected by the server because of high query rate.
 def __init__(self, username, password,token_file=None,circuit=0,**cacheDuration=0**):

**Comment by somm15** [comment]
Is it solved?

**Comment by sebekhtc** [comment]
Same here, it happens from time to time (every few days). Restarting and reinstalling the pyvicare doesn't help. I try cache duration with different values (1, 5, 10..) no change. It could be on the server side(?) One day this month they announced the maintenance work that would not affect website vitoguide but as they said it would affect the API operation. 

PS. After an hour all back to normal... probably maintenance

**Comment by ddokupil** [comment]
What does cache duration exactly do? Does it save values somewhere and will just read from it until cacheDuration expires?
Strange this is when I get KeyError: 'entities' I can still use ViCare app.
