### ISSUE TITLE
Token auto-renewal issue

### ISSUE THREAD

**Issue by oischinger** [openviess/PyViCare#49]
It seems there is an issue with token auto-renewal. The original report is here: https://github.com/home-assistant/core/issues/44084

After the token renewal the service tries to coll its own post method again but this seems to fail:
`Unexpected error for call_service at pos 1: 'ViCareCachedService' object has no attribute '_post'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 192, in __post
j=self.oauth.post(url,data,headers=h)`

With my limited python knowledge I'm not really sure what's the issue. Does ViCareCachedService somehow need to override the post method?
Would be great if you or maybe @crazyfx1 could give me a hint.

Here's the full log when the issue occurs:
`2020-12-09 15:44:49 INFO (MainThread) [homeassistant.components.automation.set_heating] set heating on when TADO requests: Running automation actions
2020-12-09 15:44:49 INFO (MainThread) [homeassistant.components.automation.set_heating] set heating on when TADO requests: Executing step call service
2020-12-09 15:44:49 INFO (MainThread) [homeassistant.components.automation.set_heating] set heating on when TADO requests: Executing step call service
2020-12-09 15:44:49 INFO (MainThread) [homeassistant.components.automation.set_temp_2] Set_temp: Running automation actions
2020-12-09 15:44:49 INFO (MainThread) [homeassistant.components.automation.set_temp_2] Set_temp: Executing step call service
2020-12-09 15:44:49 WARNING (SyncWorker_0) [ViCare] Token expired, renewing
2020-12-09 15:44:50 INFO (SyncWorker_0) [ViCare] Token serialized to /config/.storage/vicare_token.save
2020-12-09 15:44:50 INFO (SyncWorker_0) [ViCare] New token created
2020-12-09 15:44:50 INFO (SyncWorker_0) [ViCare] Token renewed successfully
2020-12-09 15:44:50 ERROR (MainThread) [homeassistant.components.automation.set_temp_2] Set_temp: Error executing script. Unexpected error for call_service at pos 1: 'ViCareCachedService' object has no attribute '_post'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 192, in __post
j=self.oauth.post(url,data,headers=h)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
url, headers, data = self._client.add_token(
File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 536, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 544, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 404, in async_set_temperature
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/vicare/climate.py", line 236, in set_temperature
self._api.setProgramTemperature(self._current_program, temp)
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareDevice.py", line 84, in setProgramTemperature
return self.service.setProperty("heating.circuits." + str(self.service.circuit) + ".operating.programs."+program,"setTemperature","{"targetTemperature":"+str(temperature)+"}")
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 237, in setProperty
return self.__post(url,data)
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 203, in __post
return self._post(url,data)
AttributeError: 'ViCareCachedService' object has no attribute '_post'
2020-12-09 15:44:50 ERROR (MainThread) [homeassistant.components.automation.set_temp_2] While executing automation automation.set_temp_2
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 192, in __post
j=self.oauth.post(url,data,headers=h)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
url, headers, data = self._client.add_token(
File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/init.py", line 433, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 536, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 544, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 404, in async_set_temperature
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/vicare/climate.py", line 236, in set_temperature
self._api.setProgramTemperature(self._current_program, temp)
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareDevice.py", line 84, in setProgramTemperature
return self.service.setProperty("heating.circuits." + str(self.service.circuit) + ".operating.programs."+program,"setTemperature","{"targetTemperature":"+str(temperature)+"}")
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 237, in setProperty
return self.__post(url,data)
File "/usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py", line 203, in __post
return self._post(url,data)
AttributeError: 'ViCareCachedService' object has no attribute 'post'
2020-12-09 15:45:34 INFO (SyncWorker_6) [PyTado.interface] api call result: ......

`

**Comment by somm15** [comment]
I will have a look as well.
Could you please edit your message and remove your access token?
Not sure it's a good idea to keep that here.

**Comment by somm15** [comment]
I found the bug. On line 203 in PyViCareService.py there is : `return self._post(url,data)`
I have to add an underscore. I don't know how it happened.
I'll fix it ASAP but I have new machine so dev environment is not ready. If someone wants to fix, I'll approve PR ASAP.

**Comment by oischinger** [comment]
I've made the fix you proposed in my Home Assistant integration. I'll let you know how it holds up.

**Comment by u450192** [comment]
@oischinger : Can I help with testing ? As I experience the problem on a daily basis :-)

**Comment by oischinger** [comment]
@u450192 how does your home assistant installation look like?
To test it you have to modify the pyvicare library in home assistant core.
It's not straight forward but i can give you instructions if you want

**Comment by u450192** [comment]
@oischinger ... Thx 4 your reply. I am running ha on a raspberry and can reach all files for upload. So if it is a file replace I can manage 😁 kr Patrick

**Comment by oischinger** [comment]
I use Home Assistant OS (Hass.io), here's what I did:
find PyVicareService.py somewhere on the disk:
`find / -iname '*PyViCareService.py*'`

In my case it was in /usr/local/lib/python3.8/site-packages/PyViCare/PyViCareService.py
Go to line 203 and change 
`return self._post(url,data)`
to
`return self.__post(url,data)`

I did not see the issue that you reported anymore when the token was refreshed, so I guess the fix is good.
@somm15  can you please release another version, then I can make a PR to home assistant

**Comment by u450192** [comment]
@oischinger thx, I will do a search and replace. Experience in cobol, assembler, apl, rpg, abap, sql ... But not yet in python 😁 kr

**Comment by u450192** [comment]
@oischinger installed SSH on my ha. But the file cannot be found. Are the files in a precompiled state on my instance? I will wait till the patch is released ,😉

**Comment by oischinger** [comment]
It seems you are running Home assistant OS. Now it becomes hard because you need to ssh to the right container. you can run the following commands then:
ssh root@IP_ADRESS -p 22222
login
docker exec -it homeassistant /bin/bash

Now you can search for the file since you are in the HA container

**Comment by u450192** [comment]
@oischinger thx ..
 Indeed, but now the connection on 22222 is refused. Seems an authorized keys needs to be created ..
 I will have a look at it when I have more time ... Anyway many thx 4 your support

**Comment by oischinger** [comment]
Yes you need to prepare your home assistant installation to open the port 22222 for that.
I'm sure that your issue is resolved with the fix, so no need for further tests I guess

**Comment by u450192** [comment]
Great thx 4 your support ... I will surely enjoy the integration. Helps my sick wife to start the heating with voice over google towards tado ... Ha ... Pyvicare ... Viessmann 😁😁😁👍

**Comment by u450192** [comment]
@oischinger @somm15 Any idea when this will be included in ha release schedule? Thx4your info

**Comment by oischinger** [comment]
@somm15  when can you upload a new release? It would be great to fix this issue in HA

**Comment by somm15** [comment]
Sorry, crazy week at work.
I'll make a new pip release tomorrow evening.
